/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.semester.pkg3;

/**
 *
 * @author MSI
 */
import javax.swing.table.DefaultTableModel;

public class dasboard extends javax.swing.JFrame {

    /**
     * Creates new form dasboard
     */
    DefaultTableModel model;
    ObatService service = new ObatService();

    public dasboard() {
        initComponents();
        setLocationRelativeTo(null); // posisi di tengah layar
        setResizable(false); // ukuran window tidak bisa diubah
        model = (DefaultTableModel) tableObat.getModel();

        menuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javax.swing.JOptionPane.showMessageDialog(
                        null,
                        "Fitur belum tersedia",
                        "Informasi",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            }
        });
        menuLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javax.swing.JOptionPane.showMessageDialog(
                        null,
                        "Fitur belum tersedia",
                        "Informasi",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            }
        });
        menuDokumentasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javax.swing.JOptionPane.showMessageDialog(
                        null,
                        "Fitur belum tersedia",
                        "Informasi",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            }
        });
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

    }

    private void refreshTable() {
        model.setRowCount(0);
        for (Obat o : service.getAll()) {
            model.addRow(new Object[]{
                o.getKodeObat(),
                o.getNamaObat(),
                o.getIdKategori(),
                o.getKodeSatuan()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Kode_Obat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nama_Obat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Id_Kategori = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Kode_Satuan = new javax.swing.JTextField();
        btnnama = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableObat = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kode_obat = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        btnnama1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        id_kategori = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kode_satuan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPembelian = new javax.swing.JMenuItem();
        menuLokasi = new javax.swing.JMenuItem();
        menuDokumentasi = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel1.setText("APLIKASI APOTEKER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Kode Obat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        Kode_Obat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kode_Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_ObatActionPerformed(evt);
            }
        });
        jPanel1.add(Kode_Obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 111, 417, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Obat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, -1, -1));

        Nama_Obat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_ObatActionPerformed(evt);
            }
        });
        jPanel1.add(Nama_Obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 146, 417, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Id Kategori");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 184, -1, -1));

        Id_Kategori.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Id_Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_KategoriActionPerformed(evt);
            }
        });
        jPanel1.add(Id_Kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 181, 417, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Kode Satuan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 219, -1, -1));

        Kode_Satuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kode_Satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_SatuanActionPerformed(evt);
            }
        });
        jPanel1.add(Kode_Satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 216, 417, -1));

        btnnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnnama.setText("TAMBAH");
        btnnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnamaActionPerformed(evt);
            }
        });
        jPanel1.add(btnnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 282, -1, -1));

        tableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Obat", "Nama Obat", "Id Kategori", "Kode Satuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableObat.setToolTipText("");
        jScrollPane1.setViewportView(tableObat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 331, 587, 369));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Edit Obat");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kode Obat");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nama");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        btnnama1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnnama1.setText("SIMPAN");
        btnnama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnama1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Id Kategori");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Kode Satuan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(btnnama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_kategori)
                            .addComponent(nama)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(kode_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addComponent(kode_satuan)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kode_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(id_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kode_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnnama1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 331, -1, 370));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kumpulan_gambar/f285e91d3c1e6a319b581e2c9cb09a97.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 260, 260));

        jMenu1.setText("Menu");

        menuPembelian.setText("Pembelian");
        menuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembelianActionPerformed(evt);
            }
        });
        jMenu1.add(menuPembelian);

        menuLokasi.setText("Lokasi Apotek");
        jMenu1.add(menuLokasi);

        menuDokumentasi.setText("Dokumentasi Aplikasi");
        menuDokumentasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDokumentasiActionPerformed(evt);
            }
        });
        jMenu1.add(menuDokumentasi);

        menuKeluar.setText("Keluar Aplikasi");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(menuKeluar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Kode_ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_ObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_ObatActionPerformed

    private void Nama_ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_ObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_ObatActionPerformed

    private void Id_KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_KategoriActionPerformed

    private void Kode_SatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_SatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_SatuanActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void btnnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnamaActionPerformed
        // TODO add your handling code here:
        Obat o = new Obat(
                Kode_Obat.getText(),
                Nama_Obat.getText(),
                Id_Kategori.getText(),
                Kode_Satuan.getText()
        );

        service.tambahObat(o);
        refreshTable();
    }//GEN-LAST:event_btnnamaActionPerformed

    private void btnnama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnama1ActionPerformed
        // TODO add your handling code here:
        String kode = kode_obat.getText();

        Obat obatBaru = new Obat(
                kode,
                nama.getText(),
                id_kategori.getText(),
                kode_satuan.getText()
        );

        boolean berhasil = service.updateObat(kode, obatBaru);

        if (berhasil) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Data obat berhasil diperbarui");
            refreshTable();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Kode obat tidak ditemukan!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnnama1ActionPerformed

    private void menuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPembelianActionPerformed

    private void menuDokumentasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDokumentasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDokumentasiActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id_Kategori;
    private javax.swing.JTextField Kode_Obat;
    private javax.swing.JTextField Kode_Satuan;
    private javax.swing.JTextField Nama_Obat;
    private javax.swing.JButton btnnama;
    private javax.swing.JButton btnnama1;
    private javax.swing.JTextField id_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kode_obat;
    private javax.swing.JTextField kode_satuan;
    private javax.swing.JMenuItem menuDokumentasi;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuLokasi;
    private javax.swing.JMenuItem menuPembelian;
    private javax.swing.JTextField nama;
    private javax.swing.JTable tableObat;
    // End of variables declaration//GEN-END:variables
}
